### ISSUE TITLE
404 on all requests to /.ghost/activitypub/v1/post/

### ISSUE THREAD

**Issue by jonathanhogg** [TryGhost/ActivityPub#1145]
If I click on any post in the admin UI – say in the Notes section – I get an "Error loading note" screen and the following in the logs:

```
activitypub-1          | 16:09:57.536 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'a9b6358b-9738-48ae-bd58-688148a15c97'
activitypub-1          | 16:09:57.545 WRN fedify·federation·http: 'GET' '/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01': 404
activitypub-1          | 16:09:57.545 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'a9b6358b-9738-48ae-bd58-688148a15c97' 404 9ms
```

The example above is for my own (first) post, but I get the same for those of accounts I'm following. This is despite the post showing correctly in the list. The embedded status ID URL within that query is correct and loads if I GET it directly.

It looks like something failing in the post repository, but the logs aren't telling me much.

For reference:

- I am running my own, self-hosted site with Docker
- I am using an ActivityPub container built from the current git HEAD, as I'm running on arm64 and there's no pre-built images for that
- I upgraded from an existing Ghost 5 installation in something of a try-things-and-see process as there was no clear documentation
- I'm using NGINX as a reverse proxy rather than Caddy
- Everything else _seems_ to be working OK…

**Comment by cathysarisky** [comment]
This is fixed in Ghost 6.0.3. Please update! :)

**Comment by jonathanhogg** [comment]
Ah! Exciting news! I am using the Docker "official" Ghost image so I'll need to wait for that to update and test (it's not even got complete 6.0.2 images yet…).

**Comment by jonathanhogg** [comment]
@cathysarisky: OK, I have updated to 6.0.3, pulled up to the tip of ActivityPub and rebuilt, but still the same 404 errors on all of the `/activitypub/v1/{posts,replies}/<status_url>` requests even though the `/activitypub/v1/feed/{notes,reader}' requests are returning a list of posts fine.

Is there some additional debugging I can jam into the backend to figure out what's going wrong?

**Comment by cathysarisky** [comment]
Any errors in ghost itself when you first start up?  Anything in the browser console (networking tab) that's failing besides these specific 404s?  I'm wondering if there's an auth failure, too.

**Comment by jonathanhogg** [comment]
OK, Ghost boot log:

```
ghost-1  | [2025-08-14 12:01:12] INFO Ghost is running in production...
ghost-1  | [2025-08-14 12:01:12] INFO Ghost is running in production...
ghost-1  | [2025-08-14 12:01:12] INFO Your site is now available on https://outputarts.com/
ghost-1  | [2025-08-14 12:01:12] INFO Ctrl+C to shut down
ghost-1  | [2025-08-14 12:01:12] INFO Ghost server started in 0.836s
ghost-1  | [2025-08-14 12:01:12] INFO Your site is now available on https://outputarts.com/
ghost-1  | [2025-08-14 12:01:12] INFO Ctrl+C to shut down
ghost-1  | [2025-08-14 12:01:12] INFO Ghost server started in 0.836s
ghost-1  | [2025-08-14 12:01:12] INFO Database is in a ready state.
ghost-1  | [2025-08-14 12:01:12] INFO Database is in a ready state.
ghost-1  | [2025-08-14 12:01:12] INFO Ghost database ready in 1.257s
ghost-1  | [2025-08-14 12:01:12] INFO Ghost database ready in 1.257s
ghost-1  | [2025-08-14 12:01:14] INFO Invalidating assets for regeneration
ghost-1  | [2025-08-14 12:01:14] INFO Invalidating assets for regeneration
ghost-1  | [2025-08-14 12:01:14] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:14] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:14] INFO Scheduling job mentions-email-report at 37 28 * * * *. Next run on: Thu Aug 14 2025 12:28:37 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:14] INFO Scheduling job mentions-email-report at 37 28 * * * *. Next run on: Thu Aug 14 2025 12:28:37 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Pinging Explore with Payload https://explore.ghost.org/api/update {"ghost":"6.0.3","site_uuid":"2487c170-2e19-4dad-93c8-e695c1cbe789","url":"https://outputarts.com/","theme":"casper-outputarts","facebook":"outputarts","twitter":null,"posts_total":50,"posts_last":"2025-07-21T11:00:00.000Z","posts_first":"2010-01-08T12:00:00.000Z"}
ghost-1  | [2025-08-14 12:01:15] INFO Pinging Explore with Payload https://explore.ghost.org/api/update {"ghost":"6.0.3","site_uuid":"2487c170-2e19-4dad-93c8-e695c1cbe789","url":"https://outputarts.com/","theme":"casper-outputarts","facebook":"outputarts","twitter":null,"posts_total":50,"posts_last":"2025-07-21T11:00:00.000Z","posts_first":"2010-01-08T12:00:00.000Z"}
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job clean-expired-comped at 29 0 4 * * *. Next run on: Fri Aug 15 2025 04:00:29 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job clean-expired-comped at 29 0 4 * * *. Next run on: Fri Aug 15 2025 04:00:29 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job clean-tokens at 8 52 19 * * *. Next run on: Thu Aug 14 2025 19:52:08 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job clean-tokens at 8 52 19 * * *. Next run on: Thu Aug 14 2025 19:52:08 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Ghost booted in 4.23s
ghost-1  | [2025-08-14 12:01:15] INFO Ghost booted in 4.23s
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Adding offloaded job to the inline job queue
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job update-check at 40 25 10 * * *. Next run on: Fri Aug 15 2025 10:25:40 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Scheduling job update-check at 40 25 10 * * *. Next run on: Fri Aug 15 2025 10:25:40 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Running milestone emails job on Sun Aug 17 2025 12:01:15 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO Running milestone emails job on Sun Aug 17 2025 12:01:15 GMT+0000 (Coordinated Universal Time)
ghost-1  | [2025-08-14 12:01:15] INFO URL Service ready in 1966ms
ghost-1  | [2025-08-14 12:01:15] INFO URL Service ready in 1966ms

ghost-1  | [2025-08-14 12:01:15] INFO Checking ActivityPub Webhook state
ghost-1  | [2025-08-14 12:01:15] INFO ActivityPub webhooks in correct state
ghost-1  | [2025-08-14 12:01:15] INFO ActivityPub webhooks in correct state
ghost-1  | [2025-08-14 12:01:16] INFO Explore Response 200 OK
ghost-1  | [2025-08-14 12:01:16] INFO Explore Response 200 OK
```

The only warnings I get on actually logging in are about TinyBird not being configured (which it isn't).

JS console logs (this is in Safari 18.6 on macOS) on opening the *Network* > *Reader* tab are:

```
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (ghost, line 11)
[Error] Source Map loading errors (x9)
[Error] Failed to load resource: the server responded with a status of 404 () (index-CNPz6XrY.mjs.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (chunk.524.9820d2bf73b62bb7dba9.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (chunk.397.f965bec6bb556d2750de.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (vendor-326b46cbc2845d47f1e0af43ba21caec.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (ghost-e1daf39ee5db5b63c0f98c9fa698f648.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (koenig-lexical.umd.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (index-qJnVka7B.mjs.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (admin-x-settings.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (index-CNPz6XrY.mjs.map, line 0)
```

Clicking on an article gives me the additional errors:

```
[Error] Failed to load resource: the server responded with a status of 404 () (https://activitypub.ghost.org/.ghost/activitypub/article/6a0b6109-f6ab-4670-9860-15d3fdc49727, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (https://activitypub.ghost.org/.ghost/activitypub/article/6a0b6109-f6ab-4670-9860-15d3fdc49727, line 0)
```

Switching to the *Notes* list and clicking on a note gives me:

```
[Error] Failed to load resource: the server responded with a status of 404 () (https://outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (https://outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01, line 0)
```

No errors or warnings from Ghost backend except for `404`/`NotFoundError` notices on those `.map` files.

Logs from `ActivityPub` on clicking on the note are:

```
activitypub-1          | 12:09:09.666 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'b7618605-ca68-436e-92f3-cf211263652e'
activitypub-1          | 12:09:09.667 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.666 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'b7618605-ca68-436e-92f3-cf211263652e'
activitypub-1          | 12:09:09.667 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.680 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/domains' '922272f8-c9bf-43ed-9e54-fec04589d389'
activitypub-1          | 12:09:09.680 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.680 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/domains' '922272f8-c9bf-43ed-9e54-fec04589d389'
activitypub-1          | 12:09:09.680 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.684 WRN fedify·federation·http: 'GET' '/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01': 404
activitypub-1          | 12:09:09.685 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'b7618605-ca68-436e-92f3-cf211263652e' 404 19ms
activitypub-1          | 12:09:09.684 WRN fedify·federation·http: 'GET' '/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01': 404
activitypub-1          | 12:09:09.685 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/replies/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'b7618605-ca68-436e-92f3-cf211263652e' 404 19ms
activitypub-1          | 12:09:09.690 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/accounts' '9afbb2c2-ef21-4abc-a689-57e904f27087'
activitypub-1          | 12:09:09.691 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.690 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/accounts' '9afbb2c2-ef21-4abc-a689-57e904f27087'
activitypub-1          | 12:09:09.691 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.709 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/domains' '922272f8-c9bf-43ed-9e54-fec04589d389' 200 29ms
activitypub-1          | 12:09:09.709 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/domains' '922272f8-c9bf-43ed-9e54-fec04589d389' 200 29ms
activitypub-1          | 12:09:09.714 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/accounts' '9afbb2c2-ef21-4abc-a689-57e904f27087' 200 24ms
activitypub-1          | 12:09:09.714 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/blocks/accounts' '9afbb2c2-ef21-4abc-a689-57e904f27087' 200 24ms
ghost-1                | [2025-08-14 12:09:09] INFO "GET /ghost/api/admin/identities/" 200 31ms
ghost-1                | [2025-08-14 12:09:09] INFO "GET /ghost/api/admin/identities/" 200 31ms
activitypub-1          | 12:09:09.761 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'be0b2968-c3ad-475f-bb30-c9c1ff3a088f'
activitypub-1          | 12:09:09.761 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'be0b2968-c3ad-475f-bb30-c9c1ff3a088f'
activitypub-1          | 12:09:09.761 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.761 INF activitypub: KnexKvStore: Get key cachedJwks,outputarts.com
activitypub-1          | 12:09:09.771 WRN fedify·federation·http: 'GET' '/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01': 404
activitypub-1          | 12:09:09.771 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'be0b2968-c3ad-475f-bb30-c9c1ff3a088f' 404 10ms
activitypub-1          | 12:09:09.771 WRN fedify·federation·http: 'GET' '/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01': 404
activitypub-1          | 12:09:09.771 INF activitypub: 'GET' 'outputarts.com' 'https://outputarts.com/.ghost/activitypub/v1/post/https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01' 'be0b2968-c3ad-475f-bb30-c9c1ff3a088f' 404 10ms
```

If I request any of those post URLs directly (e.g., `https:/outputarts.com/.ghost/activitypub/note/39511df4-de40-4175-8f77-f1bccdee1b01`) then I get back a sensible-looking lump of JSON.

[Addendum:] Only load failures in the network tab are those same two `replies`/`post` requests.

**Comment by RdrSeraphim** [comment]
I'm also noticing 404's in calls to `/.ghost/activitypub/v1/actions/bluesky/*`, similar deal with the endpoints already mentioned: no particular logging indicating an issue, nothing off in the Ghost log proper.

Edit: realized this is because the activitypub container is outdated, switching to `edge` fixed this for the bsky endpoints
